### PR TITLE
Added support for v2.16.1 and small css fix.

### PR DESCRIPTION
**Pull request by BlackDex**
- Updated patch support for v2.16.1
- Hidden an extra form for taxes (not hidden in v2.16.0 either)

bitwarden/web commit-hash: 949f61f1a46a0ce680e9a39e6240f7b66b1b6efe

### CODE REVIEW

**Comment by BlackDex** [comment]
Maybe it is better to just rename this to v2.16.0, if so, please let me know.

**Comment by dani-garcia** [comment]
Well if it does apply to 2.16.0 then it probably makes more sense to update that one instead of a new one, but it doesn't matter much becasue i won't create a new build for 2.16.0 now that a newer release exists.

Can you also update the VAULT_VERSION in the Dockerfile with the commit hash?

**Comment by BlackDex** [comment]
Sure, ill do that right now

**Comment by BlackDex** [comment]
@dani-garcia: Done

**Pull request merged**
