### PR TITLE
Update to web-vault v2022.11.1

### PR DESCRIPTION
**Pull request by BlackDex**
This PR updates the web-vault to v2022.11.1
It also replaces the main logo and top left icon to indicate it is Vaultwarden.

And the footer text has been change to `Vaultwarden (unofficial Bitwarden® server)`

This hopefully helps causing less confusion.

### CODE REVIEW

**Comment by stefan0xC** [comment]
I have not given it much attention but in 32x32px the white V is almost unrecognizable because it melts with the cog wheel. I think making it a bit less thick would make it look better so you can recognize it better, i.e.

icon-white -> vaultwarden-icon-white

**Comment by BlackDex** [comment]
@dani-garcia please hold the merge of this.
I will change the icon, including the logo's of Vaultwarden for a bit better version, thanks to @stefan0xC for pointing out the visibility.

**Comment by BlackDex** [comment]
Ok, PR is ready now. Images are changed.
Will create a new PR for the vaultwarden repo with the updated svg images.
Thanks @stefan0xC for noticing this.

**Comment by stefan0xC** [comment]
Thanks. It now looks much better:
light-mode
dark-mode

**Comment by BlackDex** [comment]
> Thanks. It now looks much better: light-mode dark-mode

And they are not wonky anymore. Now it's symmetrical.

**Comment by ecesarini** [comment]
Hi,
I'm using a custom Dockerfile to  build my web-vault. The Dockerfile is pretty similar to the one of bw_web_build repo execpt for some additions.
Dockerfile runs _scripts/apply_patches.sh_ inside the container.
If I add `COPY --chown=node:node resources /resources` inside it, will it patch cleanly my build anyway?
I'm asking beacuse I noticed some `cp -vf ../resources/* ./apps/web/src/images/*` statements inside _scripts/apply_patches.sh_

Thank you

**Comment by BlackDex** [comment]
> Hi, I'm using a custom Dockerfile to build my web-vault. The Dockerfile is pretty similar to the one of bw_web_build repo execpt for some additions. Dockerfile runs _scripts/apply_patches.sh_ inside the container. If I add `COPY --chown=node:node resources /resources` inside it, will it patch cleanly my build anyway? I'm asking beacuse I noticed some `cp -vf ../resources/* ./apps/web/src/images/*` statements inside _scripts/apply_patches.sh_
> 
> Thank you

For that to work you also need to resources of course, else it will not work. If you checkout this PR, that should work.

**Comment by ecesarini** [comment]
> > Hi, I'm using a custom Dockerfile to build my web-vault. The Dockerfile is pretty similar to the one of bw_web_build repo execpt for some additions. Dockerfile runs _scripts/apply_patches.sh_ inside the container. If I add `COPY --chown=node:node resources /resources` inside it, will it patch cleanly my build anyway? I'm asking beacuse I noticed some `cp -vf ../resources/* ./apps/web/src/images/*` statements inside _scripts/apply_patches.sh_
> > Thank you
> 
> For that to work you also need to resources of course, else it will not work. If you checkout this PR, that should work.

Sorry,
I didn't notice the addition in Dockerfile changelog.

Thank you

**Comment by ecesarini** [comment]
Just a curiosity:
when i started to deploy vaultwarden,  I sent an email support@bitwarden.com asking if it would be appropriate remove bitwarden logo from client web vault home page and leaving just my company logo instead. It was just page style purpose.
They answered me:
_As of right now we do not support swapping of logos, may I ask are you
looking to be an MSP/re-seller of Bitwarden?_

Has something changed?

**Comment by BlackDex** [comment]
Not sure why you are contacting Bitwarden regarding this.
There web-vault is OpenSource under the GPLv3 License. They also have a Trademark document which probably states what you want to know. 
See:
- https://github.com/bitwarden/clients/blob/master/LICENSE.txt
- https://github.com/bitwarden/server/blob/master/TRADEMARK_GUIDELINES.md

They probably interpreted your question into regards of there Bitwarden Self Hosted solution, which has totally nothing to do with Vaultwarden which is in no way associated with Bitwarden Inc as is stated in our README.md https://github.com/dani-garcia/bw_web_builds/blob/master/README.md

**Pull request merged**
