### PR TITLE
Remove/hide incorrect links related to Bitwarden Send

### PR DESCRIPTION
**Pull request by jjlin**
* Fixes dani-garcia/bitwarden_rs#1555
* Fixes dani-garcia/bitwarden_rs#1566

### CODE REVIEW

**Review by BlackDex — APPROVED** [review]

**Comment by lgwapnitsky** [comment]
Still receiving the issue. Ran a git pull and a cargo rebuild this morning

image

**Comment by BlackDex** [comment]
Are you sure that you are using the patched version? Looks to me like  you are using an un-patched version somehow.

**Comment by BlackDex** [comment]
Try to open: your.domain.tld/app/main.255e7d5d9d705b3e362b.css and look for `BITWARDEN_RS`

**Comment by lgwapnitsky** [comment]
[image: image.png]

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by lgwapnitsky** [comment]
***@***.***:/opt/bitwarden# git pull
Already up to date.
***@***.***:/opt/bitwarden# git remote show origin
* remote origin
  Fetch URL: https://github.com/dani-garcia/bitwarden_rs
  Push  URL: https://github.com/dani-garcia/bitwarden_rs
  HEAD branch: master
  Remote branches:
    async  tracked
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
***@***.***:/opt/bitwarden#

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by BlackDex** [comment]
The web-vault isn't part the backend, they are both separate.
I really think you do not have a right web-vault installed/compiled.

Also, attached images do not work via e-mail with github.

**Comment by lgwapnitsky** [comment]
ok.  let me update the webvault and see what happens.

Thank you

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Pull request merged**
