### PR TITLE
update web-vault to v2024.6.2 and remove bitwarden_license/ from build

### PR DESCRIPTION
**Pull request by stefan0xC**
New web-vault version: [web-v2024.6.2](https://github.com/bitwarden/clients/releases/tag/web-v2024.6.2)

There were a lot of [changes between v2024.5.1 and v2024.6.2](https://github.com/bitwarden/clients/compare/web-v2024.5.1...web-v2024.6.2) 

Since the payment method warning is now hidden behind a feature flag I've removed the code that patches it out (because the banner was also added to other parts of the code base and I think the patches are more maintainable this way). We might want to remove it manually again if the feature flag gets removed.

### CODE REVIEW

**Comment by BlackDex** [comment]
@stefan0xC, do we want to add the changes mentioned in #163 to this PR in a good way?
The main reason for not adding in the the previous one was that the tsconfig still had that path in it.
Since v2024.6.x that has been removed, and it now might be as easy as only removing that directory, and adding it to the exclude list for generating the patch.

**Comment by dfunkt** [comment]
Every time I sign in:

> vaultwarden  | [2024-06-19 12:25:35.493][request][INFO] GET /api/organizations/undefined/policies/token?token=undefined&email=undefine
vaultwarden  | [2024-06-19 12:25:35.493][vaultwarden::auth][ERROR] Token is invalid
vaultwarden  | [2024-06-19 12:25:35.493][response][INFO] (list_policies_token) GET /api/organizations/<org_id>/policies/token?<token> => 400 Bad Request

**Comment by stefan0xC** [comment]
@dfunkt That also happens on https://vault.bitwarden.com/

**Comment by stefan0xC** [comment]
Seems like the clients are now using the new `/api/ciphers/<id>/collections_v2` endpoint: 
https://github.com/bitwarden/clients/commit/5075d0865e79161577cd4a26a2b065cdb0aaa2f5#diff-4c74e6c7632b75e87220181841dce1ffac6c0b1ba3430a2766c4def0fdc7decf

**Comment by BlackDex** [comment]
> Seems like the clients are now using the new `/api/ciphers/<id>/collections_v2` endpoint: [bitwarden/clients@5075d08#diff-4c74e6c7632b75e87220181841dce1ffac6c0b1ba3430a2766c4def0fdc7decf](https://github.com/bitwarden/clients/commit/5075d0865e79161577cd4a26a2b065cdb0aaa2f5#diff-4c74e6c7632b75e87220181841dce1ffac6c0b1ba3430a2766c4def0fdc7decf)

The other clients also seem to use this currently. https://github.com/dani-garcia/vaultwarden/issues/4681
We probably need to fix this a.s.a.p.

**Comment by stefan0xC** [comment]
Updating to the new web-vault version ([`web-v2024.6.3`](https://github.com/bitwarden/clients/releases/tag/web-v2024.6.3)) will take me a few days.

**Comment by stefan0xC** [comment]
The added logo (mainly used for login screen) uses the `tw-fill-text-headers` class instead of `tw-fill-primary-600` (as the Bitwarden logo does) to prevent a blue Vaultwarden logo. As far as I've looked into it this tailwind color is not (yet) used anywhere in the web-vault (only in icons for the browser extension) so using it like this should be no problem for now.

**Comment by stefan0xC** [comment]
Since the web-vault requires a new endpoint I'd probably release a new vaultwarden version first before making a new `bw_web_builds` release (as some downstream packagers will always ship the latest release even if it's not compatible yet) or at least include a warning about that in the release notes.

**Comment by tessus** [comment]
It's impossible for a project to satisfy whetever policies they have downstream. While a new release might be a good idea anyway, I think just adding 2024.6.3 to the vw image might do the trick. In that case packagers will also understand the connection.

Btw, thanks for all your hard work. I will be in Austria this summer. Maybe I can buy you a beer...

**Comment by BlackDex** [comment]
It is also kinda chicken and egg issue here. Releasing a new Vaultwarden version should then be with an older web-vault.
After which we might want to release with the newer version just a day after or something.

We should just time it so that they are done on at least the same day.

**Comment by tessus** [comment]
IMO it is the packagers' responsibility to make sure that their packages are consistent and have dependencies in place. e.g. in RPM files you can do something like this...

This is from my webvault spec file:

```
Requires: vaultwarden >= 1.30.5^20240323.2d98aa30
```

The issue is, you cannot satisfy all requirements by all packagers or port systems. They have to make sure that their stuff is in order. It is not the upstream project dev's responsibility. Why? Because it is impossible. You might not even know all the downstream projects. Even if you do, where does it end? You have other things to worry about. While I understand the idea, it's still not doable, nor feasible.
e.g. if a packager releases something that does not work, it is not your fault, is it? Along the same lines, the same is true for packagers not releasing something.

You release when it's ready. The rest will fall into place.

**Comment by BlackDex** [comment]
I encountered some issues during testing, which is why I opted for not releasing this version.

Mainly viewing 2FA codes in the via the admin console interface doesn't seem to work.

Not sure if that is fixed if we build the current `rc` branch, which will be the next 2024.7 release soon.

It does seem to work on Bitwarden Cloud though.

**Comment by stefan0xC** [comment]
> Mainly viewing 2FA codes in the via the admin console interface doesn't seem to work.

hm... that does not seem to work in `v2024.5.1` either? I'll have to take a look what change of mine is responsible.

**Comment by BlackDex** [comment]
Well 2024.7.0 is out anyways.

**Comment by dfunkt** [comment]
2024.7.0 has been pulled back anyway, apparently new releases are scheduled for next week:
https://www.reddit.com/r/Bitwarden/comments/1e6zsm9/answers_whats_going_on_with_the_latest_release/

**Comment by stefan0xC** [comment]
Ah, thanks. I was wondering about that (why they released it twice). I hadn't noticed that they have removed it.

**Comment by lukasj98** [comment]
> Ah, thanks. I was wondering about that (why they released it twice). I hadn't noticed that they have removed it.

Now they are released again

**Comment by lukasj98** [comment]
Maybe,directly implement 7.1 ?

**Comment by stefan0xC** [comment]
@lukasj98 I'm aware but what I said above https://github.com/dani-garcia/bw_web_builds/pull/169#issuecomment-2239478617 still applies.

**Comment by BlackDex** [comment]
Technically you should be able to use style-sheets from the html/css to adjust the style of a SVG.
But that might need adjustments to the SVG then too.

Not sure how that would work correctly, never tried that before.

**Comment by stefan0xC** [comment]
@BlackDex Well, Bitwarden moved from using a class to having [two versions of the logo](https://github.com/bitwarden/clients/blob/1141bc31f48a49c4aca6324af5c8a51c4efe0462/libs/auth/src/angular/icons/bitwarden-logo.icon.ts#L3) with `fill="#175DDC"` and `fill="#FFF"` (white). We don't have to follow what they do of course but it's maybe easier with fixed values (though that requires adaption of how we replace the two logos)).

**Comment by stefan0xC** [comment]
@BlackDex since v2024.6.3 requires more changes to vaultwarden, I've decided to downgrade the web-vault to `v2024.6.2` for the time being, since that version seems to be still more compatible with Vaultwarden.

I've also backported https://github.com/bitwarden/clients/commit/71e8fdb73d935fe8d92d0da7a06aecd21e3efe2b to allow enrollment in password recovery (https://github.com/dani-garcia/vaultwarden/issues/4628). as far as I've tested it this works without any issues.

**Comment by BlackDex** [comment]
Nice! I just finished bulk collection endpoint, that seems to work. 
I'll test this PR and see if there are any hold backs for releasing.

**Comment by dfunkt** [comment]
Check the VAULT_VERSION in your latest commits, you've seemingly reverted back to v2024.5.1.

**Comment by stefan0xC** [comment]
> Every time I sign in:
> 
> > vaultwarden  | [2024-06-19 12:25:35.493][request][INFO] GET /api/organizations/undefined/policies/token?token=undefined&email=undefine
> > vaultwarden  | [2024-06-19 12:25:35.493][vaultwarden::auth][ERROR] Token is invalid
> > vaultwarden  | [2024-06-19 12:25:35.493][response][INFO] (list_policies_token) GET /api/organizations/<org_id>/policies/token? => 400 Bad Request
> 
> The vault does load up nonetheless.

hm. with `v2024.6.2` this issue returns. I'll try to look if I can backport the fix for this too.

**Comment by lukasj98** [comment]
But why not 2024.7.1

**Comment by stefan0xC** [comment]
@lukasj98 see my comments above

**Comment by polyzen** [comment]
@lukasj98 maybe you missed his earlier response https://github.com/dani-garcia/bw_web_builds/pull/169#issuecomment-2248678139

**Comment by BlackDex** [comment]
> > Every time I sign in:
> > > vaultwarden  | [2024-06-19 12:25:35.493][request][INFO] GET /api/organizations/undefined/policies/token?token=undefined&email=undefine
> > > vaultwarden  | [2024-06-19 12:25:35.493][vaultwarden::auth][ERROR] Token is invalid
> > > vaultwarden  | [2024-06-19 12:25:35.493][response][INFO] (list_policies_token) GET /api/organizations/<org_id>/policies/token? => 400 Bad Request
> > 
> > 
> > The vault does load up nonetheless.
> 
> hm. with `v2024.6.2` this issue returns. I'll try to look if I can backport the fix for this too.

I can solve this on the server-side. Tested it already so, not that big of an issue.

**Comment by ccben87** [comment]
New version out for web-vault v2024.6.3. The new version includes [PM-4154] Introduce Bulk Encrypt Service for Faster Unlock Times. I'm very keen to see this make it into Vaultwarden to see how much it improves performance!

**Comment by stefan0xC** [comment]
@ccben87 you mean [`web-v2024.7.3`](https://github.com/bitwarden/clients/releases/tag/web-v2024.7.3)? I'll probably open a new PR once this is one has been merged.

**Comment by ccben87** [comment]
> @ccben87 you mean [`web-v2024.7.3`](https://github.com/bitwarden/clients/releases/tag/web-v2024.7.3)? I'll probably open a new PR once this is one has been merged.

Ah, yes, my bad. I made a typo. I meant to say 2024.7.3. I've edited my prior comment to prevent confusion.

**Review by BlackDex — APPROVED** [review]

**Pull request merged**
